mutation createUser($name: String!, $email: String!) {
  createUser(
    input: { name: $name, email: $email }
  ) {
    id
  }
}

mutation updateUser($userId: UUID!, $name: String, $email: String, $bio: String, $phone: String, $linkedInUrl: String, $githubUrl: String, $photoUrl: String) {
  updateUser(
    id: $userId
    input: { name: $name, email: $email, bio: $bio, phone: $phone, linkedInUrl: $linkedInUrl, githubUrl: $githubUrl, photoUrl: $photoUrl }
  ) {
    id
  }
}

mutation createEducation($userId: UUID!, $degree: String!, $institution: String!, $startDate: Date!, $endDate: Date, $major: String, $minor: String, $gpa: Float, $description: String) {
  createEducation(
    input: { userId: $userId, degree: $degree, institution: $institution, startDate: $startDate, endDate: $endDate, major: $major, minor: $minor, gpa: $gpa, description: $description }
  ) {
    id
  }
}

mutation updateEducation($educationId: UUID!, $degree: String, $institution: String, $startDate: Date, $endDate: Date, $major: String, $minor: String, $gpa: Float, $description: String) {
  updateEducation(
    id: $educationId
    input: { degree: $degree, institution: $institution, startDate: $startDate, endDate: $endDate, major: $major, minor: $minor, gpa: $gpa, description: $description }
  ) {
    id
  }
}

mutation deleteEducation($educationId: UUID!) {
  deleteEducation(id: $educationId) {
    id
  }
}

mutation createExperience($userId: UUID!, $title: String!, $company: String!, $startDate: Date!, $endDate: Date, $location: String, $description: String) {
  createExperience(
    input: { userId: $userId, title: $title, company: $company, startDate: $startDate, endDate: $endDate, location: $location, description: $description }
  ) {
    id
  }
}

mutation updateExperience($experienceId: UUID!, $title: String, $company: String, $startDate: Date, $endDate: Date, $location: String, $description: String) {
  updateExperience(
    id: $experienceId
    input: { title: $title, company: $company, startDate: $startDate, endDate: $endDate, location: $location, description: $description }
  ) {
    id
  }
}

mutation deleteExperience($experienceId: UUID!) {
  deleteExperience(id: $experienceId) {
    id
  }
}

mutation createProject($userId: UUID!, $title: String!, $description: String!, $technologiesUsed: [String], $demoUrl: String, $repositoryUrl: String, $imageUrl: String) {
  createProject(
    input: { userId: $userId, title: $title, description: $description, technologiesUsed: $technologiesUsed, demoUrl: $demoUrl, repositoryUrl: $repositoryUrl, imageUrl: $imageUrl }
  ) {
    id
  }
}

mutation updateProject($projectId: UUID!, $title: String, $description: String, $technologiesUsed: [String], $demoUrl: String, $repositoryUrl: String, $imageUrl: String) {
  updateProject(
    id: $projectId
    input: { title: $title, description: $description, technologiesUsed: $technologiesUsed, demoUrl: $demoUrl, repositoryUrl: $repositoryUrl, imageUrl: $imageUrl }
  ) {
    id
  }
}

mutation deleteProject($projectId: UUID!) {
  deleteProject(id: $projectId) {
    id
  }
}
